In [1]:
# ==========================================
# Import Required Libraries
# ==========================================

import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# ==========================================
# Load Cleaned Healthcare Dataset
# ==========================================

df = pd.read_csv("../data/processed/ckd_cleaned.csv")

# Display first rows
df.head()

,id,age,bp,sg,al,su,pc,pcc,ba,bgr,...,wbcc,rbcc,htn,dm,cad,appet,pe,ane,class,Unnamed: 26
0,1,48.0,80.0,1.020,1.0,0.0,normal,notpresent,notpresent,121.0,...,7800.0,5.2,yes,yes,no,good,no,no,ckd,NaN
1,2,7.0,50.0,1.020,4.0,0.0,normal,notpresent,notpresent,121.0,...,6000.0,4.8,no,no,no,good,no,no,ckd,NaN
2,3,62.0,80.0,1.010,2.0,3.0,normal,notpresent,notpresent,423.0,...,7500.0,4.8,no,yes,no,poor,no,yes,ckd,NaN
3,4,48.0,70.0,1.005,4.0,0.0,abnormal,present,notpresent,117.0,...,6700.0,3.9,yes,no,no,poor,yes,yes,ckd,NaN
4,5,51.0,80.0,1.010,2.0,0.0,normal,notpresent,notpresent,106.0,...,7300.0,4.6,no,no,no,good,no,no,ckd,NaN

In [ ]:
# Dataset shape

print(df.shape)

(400, 26)

In [ ]:
# Missing value check

print(df.isnull().sum())

id               0
age              0
bp               0
sg               0
al               0
su               0
pc               0
pcc              0
ba               0
bgr              0
bu               0
sc               0
sod              0
pot              0
hemo             0
pcv              0
wbcc             0
rbcc             0
htn              0
dm               0
cad              0
appet            0
pe               0
ane              0
class            0
Unnamed: 26    399
dtype: int64

In [ ]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           400 non-null    int64
 1   age          400 non-null    float64
 2   bp           400 non-null    float64
 3   sg           400 non-null    float64
 4   al           400 non-null    float64
 5   su           400 non-null    float64
 6   pc           400 non-null    str
 7   pcc          400 non-null    str
 8   ba           400 non-null    str
 9   bgr          400 non-null    float64
 10  bu           400 non-null    float64
 11  sc           400 non-null    float64
 12  sod          400 non-null    float64
 13  pot          400 non-null    float64
 14  hemo         400 non-null    float64
 15  pcv          400 non-null    float64
 16  wbcc         400 non-null    float64
 17  rbcc         400 non-null    float64
 18  htn          400 non-null    str
 19  dm           400 non-null    str
 20  cad          400 non-null    str
 21  appet        400 non-null    str
 22  pe           400 non-null    str
 23  ane          400 non-null    str
 24  class        400 non-null    str
 25  Unnamed: 26  1 non-null      str
dtypes: float64(14), int64(1), str(11)
memory usage: 81.4 KB

In [ ]:
# ==========================================
# Remove Hidden Spaces From Column Names
# ==========================================

df.columns = df.columns.str.strip()

In [ ]:
# ==========================================
# Identify Categorical Columns
# ==========================================

categorical_cols = df.select_dtypes(include='object').columns

print(categorical_cols)

Index(['pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'class',
       'Unnamed: 26'],
      dtype='str')

C:\Users\user\AppData\Local\Temp\ipykernel_18112\191314192.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns

In [ ]:
# ==========================================
# Initialize Label Encoder
# ==========================================

label_encoder = LabelEncoder()

# ==========================================
# Encode Categorical Features
# ==========================================

for col in categorical_cols:
    
    # Convert categorical labels into numerical values
    df[col] = label_encoder.fit_transform(df[col])

In [ ]:
# ==========================================
# Display Encoded Dataset
# ==========================================

df.head()

,id,age,bp,sg,al,su,pc,pcc,ba,bgr,...,wbcc,rbcc,htn,dm,cad,appet,pe,ane,class,Unnamed: 26
0,1,48.0,80.0,1.020,1.0,0.0,1,0,0,121.0,...,7800.0,5.2,1,1,0,0,1,0,0,1
1,2,7.0,50.0,1.020,4.0,0.0,1,0,0,121.0,...,6000.0,4.8,0,0,0,0,1,0,0,1
2,3,62.0,80.0,1.010,2.0,3.0,1,0,0,423.0,...,7500.0,4.8,0,1,0,2,1,1,0,1
3,4,48.0,70.0,1.005,4.0,0.0,0,1,0,117.0,...,6700.0,3.9,1,0,0,2,2,1,0,1
4,5,51.0,80.0,1.010,2.0,0.0,1,0,0,106.0,...,7300.0,4.6,0,0,0,0,1,0,0,1

In [ ]:
df.to_csv(
    "../data/processed/ckd_encoded.csv",
    index=False
)

In [2]:
##Load encoded dataset
df = pd.read_csv("../data/processed/ckd_encoded.csv")

In [3]:
# ==========================================
# Separate Features and Target Variable
# ==========================================

X = df.drop("class", axis=1)

y = df["class"]

In [4]:
# ==========================================
# Initialize StandardScaler
# ==========================================

scaler = StandardScaler()

# ==========================================
# Standardize Feature Variables
# ==========================================

X_scaled = scaler.fit_transform(X)